ministryofjustice/staff-device-shared-services-infrastructure

main.tf
Creates two repos:
- Grafana repo
- Grafana image renderer repo
=> creates Grafana repositories for Grafana images

README.md, main.tf
re-uses the `ci-pipeline` module to create the pipeline
also updates the README
=> creates Pipeline for private dns zone repository

main.tf
a new repo was created for IMA Kubernetes deployments
=> creates AWS Codebuild Pipeline for the new repo

main.tf
Build pipelines for infrastructure, servers and admin
=> Network access control service

main.tf
update the prefix from smtp to net-svcs
=> updates naming convention for the network services repo

main.tf
This requires newer docker-compose features
=> set the docker image version for nac-admin and nac-server

README.md, main.tf, modules/ci-pipeline/codepipeline_with_auto_approval.tf
Also move plan step from NACS server repo to NACS infrastructure repo.
=> Document CI pipeline flags

.terraform.lock.hcl, README.md, main.tf, modules/cloudtrail/main.tf
This bumps Terraform from 0.13.7 to 1.1.7
=> Upgrade Terraform version

main.tf, versions.tf
Move terraform version configuration into separate file as per the Terraform convention.
Set the terraform required_version to 1.1.7
=> Separate required versions

README.md
Information about CI/CD has been added as per the requirement in https://github.com/ministryofjustice/nvvs-devops/issues/199
=> CI/CD info added to READMME as per Issue 199

.gitignore, scripts/ensure_cloudwatch_log_retention_policies.sh, scripts/s3_versioning_audit.sh
This script will write a file with a report on the s3 bucket versioning status for all buckets within an AWS Account.
=> 88 s3 bucket versioning audit

.env, Makefile, aws_codepipeline_dns_dhcp.tf, aws_codepipeline_logs.tf, aws_codepipeline_nac.tf, aws_codepipeline_smtp.tf, data.tf, locals.tf, logs.tf, scripts/get_secrets.sh, secrets.tf, tf-state-mgt.tf, variables.tf
How to test:
Pull this branch
`git checkout feature/aws_secrets_manager_replace_tfvars`
Set Terraform version
`tfenv use $(cat versions.tf 2> /dev/null | grep required_version | cut -d "\"" -f 2 | cut -d " " -f 2) && tfenv pin`
Run commands 
`make init`
`make workspace-select`
`make plan`
Test script
`./scripts/get_secrets.sh`
=> Feature aws secrets manager replace tfvars

Makefile, modules/ci-pipeline-webhook/s3-bucket.tf
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_s3_bucket_versioning" "client-tf-state" {
+ bucket = "pttp-ci-infrastructure-nac-admin-client-core-tf-state"
+ id     = (known after apply)
+ versioning_configuration {
+ mfa_delete = (known after apply)
+ status     = "Enabled"
}
}
+ resource "aws_s3_bucket_versioning" "client-tf-state" {
+ bucket = "pttp-ci-infrastructure-nac-client-core-tf-state"
+ id     = (known after apply)
+ versioning_configuration {
+ mfa_delete = (known after apply)
+ status     = "Enabled"
}
}
+ resource "aws_s3_bucket_versioning" "client-tf-state" {
+ bucket = …
```
=> 457 add s3 bucket versioning to remaining buckets

main.tf, tf-state-mgt.tf, variables.tf
Added IAC code for the nvvs-devops-monitor TF state bucket & TF dynamodb table.
=> Added IAC for nvvs-devops-monitor

main.tf, tf-state-mgt.tf
- Added IAC for S3 state bucket and dynamo DB table for github teams repo
=> Added IAC for github team repo

locals.tf, modules/s3-assume-role/main.tf, modules/s3-assume-role/outputs.tf, modules/s3-assume-role/variables.tf, mojo_file_transfer.tf, outputs.tf
- Create cross account assume role for S3 bucket access from development,pre-prod and production environment
=> S3 bucket file transfer role

Makefile
This change introduces the common format adopted which includes using Dosck tooling container for consistency.
make init will also select the correct workspace.
=> Baselined the Makefile

aws_codepipeline_logs.tf, modules/ci-assume-role/main.tf
Added IAM polocy permissions, to allow codebuild to get AWS secrets
=> Code build to access secrets store

aws_codepipeline_dns_dhcp.tf
Updated docker image to standard:7.0 to accommodate --platform tag in docker image
ND-159
=> Docker image update

aws_codepipeline_smtp.tf
ND170 Added docker image to module block
=>  Added docker image to module block

aws_codepipeline_dns_dhcp.tf, aws_codepipeline_smtp.tf, modules/ci-pipeline-webhook/main.tf, modules/ci-pipeline-webhook/variables.tf
https://docs.docker.com/desktop/install/linux-install/
=> docker requires at least 4gb of RAM according to docs

aws_codepipeline_smtp.tf
Added manual stage to network services pipeline to prevent pipeline running to production unchecked
=> Added manual stage to network services pipeline 

aws_codepipeline_logs.tf, modules/ci-pipeline-webhook/dynamodb.tf
- added codepipeline module back in 
- code creates a role used by other pipelines.
=> Ft codepipeline logs module

modules/cloudtrail/main.tf
Added block public access resource to bucket that had it missing.
=> Block public access to s3

modules/secrets-staff-infrastructure-certificate-services/locals.tf, modules/secrets-staff-infrastructure-certificate-services/outputs.tf, modules/secrets-staff-infrastructure-certificate-services/secrets_pre_production.tf, modules/secrets-staff-infrastructure-certificate-services/secrets_production.tf, modules/secrets-staff-infrastructure-certificate-services/variables.tf, scripts/get_secrets.sh, secrets_staff_infrastructure_certificate_services.tf
=> AWS Secrets Manager entries for supported-application = "staff-infrastructure-certificate-services"

aws_codepipeline_dns_dhcp.tf, bootstrap/remote_state.tf
Removed 'production-plan' stage from dhcp admin portal pipeline as it is not needed. 
No terraform file.
=> Nd 462 - remove production-plan stage from pipeline

modules/secrets-staff-infrastructure-certificate-services/secrets_production.tf
Adds a new Secret `ms_teams_webhook_url` for the staff-infrastructure-certificate-services repository.
=> Adds `ms_teams_webhook_url` secret

renovate.json
Disabled renovate bot as part of ND-766
=> Nd 766 disable renovate bot for specific repositories
